/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#a8c7ff',
        'accent-soft': '#a8c7ff',
        'text-secondary': '#cfcfcf',
        'on-primary-fixed': '#000000',
        secondary: '#b8c8da',
        'on-secondary-container': '#a7b7c8',
        'on-primary-container': '#6185bd',
        'tertiary-container': '#002116',
        background: '#1c222b',
        'surface-variant': '#3d4450',
        'surface-dim': '#1c222b',
        'error-container': '#93000a',
        error: '#ffb4ab',
        'on-tertiary-fixed': '#002116',
        'on-surface-variant': '#b8bcc8',
        'on-secondary': '#223240',
        'outline-variant': '#525865',
        'on-tertiary-fixed-variant': '#00513c',
        'surface-container': '#282f39',
        'surface-tint': '#a7c8ff',
        'primary-container': '#0a2444',
        'tertiary-fixed-dim': '#00e1ab',
        'surface-container-high': '#323944',
        'surface-bright': '#464d5a',
        'tertiary-fixed': '#36ffc4',
        'inverse-primary': '#3a5f94',
        tertiary: '#00e1ab',
        'surface-container-highest': '#3d4450',
        outline: '#8e9099',
        'secondary-container': '#394857',
        'on-surface': '#dfe2eb',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        surface: '#1c222b',
        'secondary-fixed': '#d4e4f6',
        'on-tertiary': '#003828',
        'on-secondary-fixed': '#0d1d2a',
        'on-tertiary-container': '#009671',
        'on-background': '#dfe2eb',
        'surface-container-lowest': '#161b24',
        'on-primary-fixed-variant': '#1f477b',
        'secondary-fixed-dim': '#b8c8da',
        'primary-fixed': '#d5e3ff',
        'on-secondary-fixed-variant': '#394857',
        'surface-container-low': '#232a34',
        'inverse-on-surface': '#343a44',
        'on-primary': '#003061',
        'primary-fixed-dim': '#a7c8ff',
        'inverse-surface': '#dfe2eb',
      },
      fontFamily: {
        sans: [
          '"Nunito Sans"',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        headline: [
          '"Nunito Sans"',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        body: [
          '"Nunito Sans"',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        label: [
          '"Nunito Sans"',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
      },
      borderRadius: {
        DEFAULT: '16px',
        sm: '12px',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '20px',
        full: '9999px',
      },
      spacing: {
        '4': '1rem',
        '8': '2rem',
        '12': '3rem',
        '16': '4rem',
        '24': '6rem',
        '32': '8rem',
      },
    },
  },
  plugins: [],
}
